import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { heroes, companions, type HeroChoice, type CompanionChoice } from '../domain/party'
import { Brand } from './Brand'
import { AdventureMode, modes } from './AdventureModes'
import { FirstQuest } from './FirstQuest'
import { PlayerAvatar, PetAvatar, type LearnerProfile } from './WelcomeQuest'
import { ArrowRight, Check, Coins, Compass, Gamepad2, Home, Sparkles, Star, UserRound, Users } from './PixelIcons'

type Page = 'Home'|'Games'|'Quests'|'Rooms'|'Progress'|'Workshop'|'Profile'
type Progress = {bridge:boolean;best:Record<string,number>}
const progressKey='pixed-adventures-v1'
function loadProgress():Progress {try{const raw=JSON.parse(localStorage.getItem(progressKey)??'null');return {bridge:raw?.bridge===true,best:Object.fromEntries(modes.map(m=>[m.id,Number.isInteger(raw?.best?.[m.id])&&raw.best[m.id]>=0&&raw.best[m.id]<=3?raw.best[m.id]:0]))}}catch{return {bridge:false,best:{}}}}
const pages:Array<[Page,typeof Home]>=[['Home',Home],['Games',Gamepad2],['Quests',Compass],['Rooms',Users],['Progress',Star],['Workshop',Sparkles],['Profile',UserRound]]
export function PlayerWorld({profile,onEdit,onUpdate,onExit}:{profile:LearnerProfile;onEdit:()=>void;onUpdate:(p:LearnerProfile)=>void;onExit:()=>void}) {
  const [page,setPage]=useState<Page>('Home'), [filter,setFilter]=useState('All'), [active,setActive]=useState<string|null>(null), [progress,setProgress]=useState(loadProgress)
  const [petName,setPetName]=useState(profile.petName),[saved,setSaved]=useState(false),[greeting,setGreeting]=useState(false)
  const [moreOpen,setMoreOpen]=useState(false)
  useEffect(()=>{setPetName(profile.petName)},[profile.petName])
  useEffect(()=>{setSaved(false)},[profile.pet])
  const mastered=Object.values(progress.best).filter(n=>n===3).length
  const points=Object.values(progress.best).reduce((a,b)=>a+b,0)
  const xp=points*10+(progress.bridge?40:0),coins=20+points*2+(progress.bridge?10:0)
  const saveProgress=(update:(p:Progress)=>Progress)=>{setProgress(p=>{const next=update(p);localStorage.setItem(progressKey,JSON.stringify(next));return next})}
  const navigate=(next:Page)=>{setMoreOpen(false);setPage(next);window.scrollTo({top:0,behavior:'instant'})}
  const party=<div className={`world-party ${greeting?'party-greeting':''}`}><PlayerAvatar choice={profile.avatar} large/><PetAvatar choice={profile.pet} large/></div>
  const cards=<><div className="world-section-heading"><div><span className="eyebrow">SMALL STEPS. BIG DISCOVERIES.</span><h2>Choose your adventure</h2></div><span className="catalog-count">6 worlds · solo practice</span></div><div className="subject-filters" aria-label="Filter games by subject">{['All','Coding','Math','Science','Logic'].map(f=><button aria-pressed={filter===f} key={f} onClick={()=>setFilter(f)} className={filter===f?'active':''}>{f}</button>)}</div><div className="world-game-grid">{modes.filter(m=>filter==='All'||m.subject===filter).map((m,i)=><motion.article key={m.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.035}} className="world-game-card"><div className="world-thumb"><div style={{backgroundPosition:m.image}}/><span>{m.subject}</span>{progress.best[m.id]===3&&<b><Check/> Mastered</b>}</div><div className="world-card-copy"><small>{m.label}</small><h3>{m.title}</h3><p>{m.blurb}</p><footer><span>3 checkpoints</span><button onClick={()=>setActive(m.id)} aria-label={`Play ${m.title}`}>Play <ArrowRight/></button></footer></div></motion.article>)}</div></>
  const trophies=[{name:'First crossing',note:'Complete the first coding loop.',earned:progress.bridge,icon:Compass},{name:'Sharp thinker',note:'Finish any adventure with 3/3.',earned:mastered>0,icon:Star},{name:'World scholar',note:'Master all six adventures.',earned:mastered===6,icon:Sparkles}]
  return <div className="player-world"><header className="world-header"><button className="brand-button" onClick={onExit} aria-label="PiXed entrance"><Brand/></button><div className="world-balance"><span><Coins/>{coins}</span><span><Star/>{xp} XP</span><button onClick={()=>navigate('Profile')} aria-label="Open my profile"><PlayerAvatar choice={profile.avatar}/><b>{profile.name}</b></button></div></header>
    <div className="world-layout"><aside className="world-nav"><span className="eyebrow">YOUR WORLD</span><nav aria-label="Your world">{pages.map(([label,Icon])=><button key={label} aria-label={label} aria-current={page===label?'page':undefined} className={`${page===label?'active':''} ${['Rooms','Progress','Workshop'].includes(label)?'secondary-mobile':''}`} onClick={()=>navigate(label)}><Icon/><span>{label}</span>{label==='Quests'&&!progress.bridge&&<i/>}</button>)}<button className={`mobile-more ${['Rooms','Progress','Workshop'].includes(page)?'active':''}`} aria-label="More pages" aria-expanded={moreOpen} aria-controls="mobile-more-menu" onClick={()=>setMoreOpen(!moreOpen)}><span aria-hidden="true" className="more-dots">•••</span><span>More</span></button></nav>{moreOpen&&<div id="mobile-more-menu" className="mobile-more-menu" onKeyDown={event=>{if(event.key==='Escape'){setMoreOpen(false);document.querySelector<HTMLButtonElement>('[aria-controls="mobile-more-menu"]')?.focus()}}}>{pages.filter(([label])=>['Rooms','Progress','Workshop'].includes(label)).map(([label,Icon])=><button key={label} aria-current={page===label?'page':undefined} onClick={()=>navigate(label)}><Icon/>{label}</button>)}</div>}<div className="nav-note"><PetAvatar choice={profile.pet}/><p>A little practice<br/>goes a long way.</p></div></aside>
      <main className="world-main"><AnimatePresence mode="wait"><motion.div key={page} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.18}}>
      {page==='Home'&&<><section className="world-welcome"><div><span className="eyebrow">WELCOME BACK, {profile.name.toUpperCase()}</span><h1>Ready for a little<br/><em>discovery?</em></h1><p>Your companion is ready. Pick a short adventure and learn something new together.</p><button className="soft-button" onClick={()=>setActive(progress.bridge?'flag':'bridge')}>{progress.bridge?'Explore the flag trail':'Start your first quest'}<ArrowRight/></button></div><div className="welcome-party">{party}<span className="party-caption">{heroes[profile.avatar].name} & {profile.petName}</span><button onClick={()=>setGreeting(v=>!v)} aria-label="Greet my companion">{greeting?`${profile.petName} is happy to see you!`:`Say hello to ${profile.petName}`} <Sparkles/></button></div></section><div className="journey-strip"><span><Compass/> Your next step</span><b>{progress.bridge?'Discover the six practice worlds':'The quiet bridge · Learn your first loop'}</b><button onClick={()=>navigate('Quests')}>View quests <ArrowRight/></button></div>{cards}</>}
      {page==='Games'&&cards}
      {page==='Quests'&&<><div className="page-intro"><span className="eyebrow">ONE QUEST AT A TIME</span><h1>Your learning path</h1><p>Start with a small coding lesson, then explore at your own pace.</p></div><div className="quest-list"><button onClick={()=>setActive('bridge')}><span className="quest-number">{progress.bridge?<Check/>:'01'}</span><div><small>CODING · BEGINNER</small><h3>The quiet bridge</h3><p>Use repeat() to guide {profile.petName} across four stepping stones.</p></div><ArrowRight/></button>{modes.map((m,i)=><button key={m.id} onClick={()=>setActive(m.id)}><span className="quest-number">{progress.best[m.id]===3?<Check/>:String(i+2).padStart(2,'0')}</span><div><small>{m.subject.toUpperCase()} · {progress.best[m.id]??0}/3 BEST</small><h3>{m.title}</h3><p>{m.blurb}</p></div><ArrowRight/></button>)}</div></>}
      {page==='Rooms'&&<><div className="page-intro"><span className="eyebrow">BETTER TOGETHER</span><h1>A place for your party</h1><p>Online rooms are still in development. You can practise the team modes on your own today.</p></div><div className="rooms-scene"><PlayerAvatar choice="girl" large/><PetAvatar choice="fox" large/><PlayerAvatar choice="boy" large/><PetAvatar choice="bot" large/></div><div className="world-info-panel"><Users/><h2>Prepare for the team adventure</h2><p>Team Battle and Capture the Flag currently offer solo practice with immediate explanations. Live invitations, room codes and multiplayer are not connected yet.</p><button className="soft-button" onClick={()=>setActive('battle')}>Try Team Battle practice <ArrowRight/></button></div></>}
      {page==='Progress'&&<><div className="page-intro"><span className="eyebrow">GROW AT YOUR OWN PACE</span><h1>Look how far you’ve come</h1><p>Your own best results, earned through learning. Replaying never removes progress.</p></div><div className="progress-stats"><div><Star/><b>{xp}</b><span>Learning XP</span></div><div><Gamepad2/><b>{mastered}/6</b><span>Worlds mastered</span></div><div><Coins/><b>{coins}</b><span>Coins earned + starter gift</span></div></div><div className="world-section-heading"><h2>Your collection</h2><span>Earned, never random</span></div><div className="trophy-grid">{trophies.map(({name,note,earned,icon:Icon})=><article key={name} className={earned?'earned':''}><Icon/><small>{earned?'UNLOCKED':'TO DISCOVER'}</small><h3>{name}</h3><p>{note}</p></article>)}</div><div className="personal-results"><h2>Personal bests</h2>{modes.map(m=><div key={m.id}><span>{m.title}</span><meter aria-label={`${m.title} personal best`} min={0} max={3} value={progress.best[m.id]??0}/><b>{progress.best[m.id]??0}/3</b></div>)}</div><p className="local-note">Progress is saved in this browser. Global rankings will arrive with online accounts.</p></>}
      {page==='Workshop'&&<><div className="page-intro"><span className="eyebrow">MAKE IT YOURS</span><h1>Your little adventuring party</h1><p>Choose your hero, meet your companion and give them a name.</p></div><div className="workshop-layout"><div className="workshop-stage">{party}<span>{profile.name} & {profile.petName}</span></div><div className="world-info-panel"><span className="eyebrow">YOUR ACTIVE PARTY</span><h2>{heroes[profile.avatar].name} & {profile.petName}</h2><p>{heroes[profile.avatar].detail} {companions[profile.pet].detail}</p><h2>Your explorer colors</h2><div className="outfit-options">{['original','forest','sunset','ocean'].map(tone=><button key={tone} className={`outfit-${tone}`} aria-label={`${tone} outfit`} aria-pressed={(profile.outfit??'original')===tone} onClick={()=>onUpdate({...profile,outfit:tone})}>{(profile.outfit??'original')===tone&&<Check/>}<span>{tone}</span></button>)}</div><h2>Companion name</h2><label className="pet-name-field">What should we call your companion?<input maxLength={18} value={petName} onChange={e=>{setPetName(e.target.value);setSaved(false)}}/></label><button className="soft-button" disabled={!petName.trim()} onClick={()=>{onUpdate({...profile,petName:petName.trim()});setSaved(true)}}>{saved?<><Check/> Saved</>:<>Save name <Check/></>}</button><p role="status">{saved?'Your companion’s name is saved.':'Names can be changed whenever you like.'}</p><button className="text-button" onClick={onEdit}>Choose another hero or pet <ArrowRight/></button></div></div><section className="party-collection"><div className="world-section-heading"><div><span className="eyebrow">FOUR WAYS TO EXPLORE</span><h2>Meet your heroes</h2></div><span>Switch freely · progress stays</span></div><div className="collection-grid">{(Object.keys(heroes) as HeroChoice[]).map(id=><button key={id} aria-pressed={profile.avatar===id} onClick={()=>onUpdate({...profile,avatar:id})} className={profile.avatar===id?'selected':''}><PlayerAvatar choice={id} large original/><small>{heroes[id].role}</small><h3>{heroes[id].name}</h3><b>{heroes[id].benefit}</b><p>{heroes[id].detail}</p><span>{profile.avatar===id?'In your party':'Choose hero'} <Check/></span></button>)}</div><div className="world-section-heading"><div><span className="eyebrow">ALWAYS BY YOUR SIDE</span><h2>A small friend. A little help.</h2></div></div><div className="collection-grid companion-collection">{(Object.keys(companions) as CompanionChoice[]).map(id=><button key={id} aria-pressed={profile.pet===id} onClick={()=>onUpdate({...profile,pet:id,petName:profile.pet===id?profile.petName:companions[id].name})} className={profile.pet===id?'selected':''}><PetAvatar choice={id} large/><small>{companions[id].label}</small><h3>{companions[id].name}</h3><b>{companions[id].benefit}</b><p>{companions[id].detail}</p><span>{profile.pet===id?'By your side':'Choose companion'} <Check/></span></button>)}</div></section></>}
      {page==='Profile' &&<><div className="page-intro"><span className="eyebrow">YOUR PLAYER CARD</span><h1>Hello, {profile.name}.</h1><p>A place for your interests, your party and your learning journey.</p></div><div className="profile-summary">{party}<div><span className="eyebrow">{profile.learnerType.toUpperCase()}</span><h2>{profile.name}</h2><p>{profile.favoriteSubject} · Age {profile.age} · Companion: {profile.petName}</p><p>Your learning style reflects your introductory choices and can change as you explore.</p><button className="soft-button" onClick={onEdit}>Edit profile & revisit questions <ArrowRight/></button></div></div><div className="world-info-panel"><h2>Your profile stays on this device</h2><p>This is a local player profile. Email login, account recovery and syncing across devices are not available yet.</p><button className="text-button" onClick={()=>navigate('Progress')}>See my progress <ArrowRight/></button></div></>}
      </motion.div></AnimatePresence><footer className="world-footer"><Brand/><span>Learn something. Try something. Become a little more you.</span></footer></main>
    </div>
    {active==='bridge'&&<FirstQuest hero={profile.avatar} pet={profile.pet} onClose={()=>setActive(null)} onComplete={()=>saveProgress(p=>({...p,bridge:true}))}/>}
    {active&&active!=='bridge'&&<AdventureMode id={active} profile={profile} onClose={()=>setActive(null)} onFinish={(id,score)=>saveProgress(p=>({...p,best:{...p.best,[id]:Math.max(p.best[id]??0,score)}}))}/>}
  </div>
}
